[[ch:ch0]]
== Введение

Как следует из названия, Message Passing Interface (https://www.mpi-forum.org), определяет программный интерфейс библиотек высокопроизводительной передачи сообщений. Включает операции двусторонних обменов (point-to-point), односторонних обменов (one-sided remote memory access) и коллективные операции. Вводит понятия группы процессов, коммуникаторов, виртуальных топологий и производных типов данных. Основное предназначение стандарта – обеспечить возможность создания параллельных программ, переносимых на уровне исходного кода между вычислительными системами различных архитектур и конфигураций: с общей и распределенной памятью, на базе заказного оборудования и свободно доступного на рынке, с процессорами общего назначения и/или специализированными ускорителями.

Изначальная мотивация создания стандарта – сложность переносимости параллельных программ между различными архитектурами вычислительных систем. К 1992 году каждый производитель высокопроизводительных вычислительных систем (Thinking Machines, NEC, Intel, Cray, Fujitsu, Hitachi), как правило, поставлял свою реализацию сред параллельного программирования, которые включали механизмы управления процессами и предоставляли операции двусторонних и коллективных обменов информацией. Можно выделить следующие проекты и программные системы, которые оказали значительное влияние на становление MPI: проект PVM (Parallel Virtual Machine) – открытая библиотека и среда времени выполнения для создания параллельных программ в модели передачи сообщений (двусторонние и ряд коллективных операций, уведомления об отказах), разработка Окриджской национальной лаборатории США (ORNL); проекты p4 (Аргонская национальная лаборатория США, ANL), Intel NX/2, IBM EUI, nCUBE Vertex, Zipcode, PARMACS, Express, Chimp, PICL, Chameleon.

Желание обобщить накопленный опыт и сформировать устойчивый интерфейс для создания параллельных программ привел в 1992 году к возникновению инициативной группы специалистов – MPI Forum, которая включала более 40 организаций и 60 человек. В мае 1994 года была опубликована первая версия стандарта, которая включала блокирующие и неблокирующие функции двусторонних обменов, коллективные операции, управление группами процессов и коммуникаторами, виртуальные топологии и производные типы данных. Эталонная реализация стандарта (reference implementation) вышла в 1996 году – библиотека MPICH. В июле 1997 года закончена работа и опубликован стандарт MPI 2.0, который включал функции односторонних обменов (one-sided communication), динамического порождения процессов, параллельный ввод-вывод (MPI I/O), интерфейсы для C++ и Fortran 90. Значительные изменения в стандарте произошли в версии MPI 3.0, которая опубликована в сентябре 2012 года. Основные изменения коснулись введения неблокирующих коллективных операций (nonblocking collective operation), разреженных коллективных операций (sparse collectives), расширения возможностей односторонних обменов, удалена поддержка интерфейса для С++. В июне 2021 года вышел MPI 4.0, который расширил интерфейс операциями с поддержкой large-count, решающий проблему переполнения знакового типа int для элементов count, коллективные операции с не меняющимися аргументами (persistent collectives), разделенные коммуникационные операции для многопоточных программ (partitioned communications) и модель сессий для инициализации MPI-программ (MPI Session).

Автор считает важным отметим, что в СССР и России велись и ведутся работы по созданию отечественных вычислительных систем с распределенной памятью и систем параллельного программирования для них: вычислительные системы с программируемой структурой (Минск-222, семейство МИКРОС)  <<bib-evr66,[1]>>,<<bib-khor78,[2]>>,<<bib-korneev85,[3]>>,<<bib-Monakhov2000,[4]>>,<<bib-Khor2008Arch,[5]>> , семейство систем МВС  <<bib-Levin1995,[6]>> , вычислительные системы со специализированными топологиями коммуникационных сетей  <<bib-Stepanenko2016,[7]>>,<<bib-Angara2019,[8]>>, реконфигурируемые вычислительные системы  <<bib-Kalaev2009,[9]>> . Автор монографии является членом научной школы по распределенным вычислительным системам с программируемой структурой, основателем которой является чл.-корр. РАН В.Г. Хорошевский. В начале 1960-х годов в Институте математики Сибирского отделения РАН были инициированы работы по созданию вычислительных систем с распределенной памятью на базе серийных ЭВМ. Для их сопряжения в систему были разработаны аппаратные системные устройства, поддерживающий основные типы коммуникационных операций: двусторонние обмены и коллективные операции: трансляционный обмен (one-to-all), коллекторный прием (all-to-one) и трансляционно-циклический обмен типа "каждый-всем" (all-to-all). Заинтересованный читатель может найти дополнительную информацию в следующих работах  <<bib-evr66,[1]>>,<<bib-khor78,[2]>>,<<bib-korneev85,[3]>>,<<bib-Khor2008Arch,[5]>> .

В центре внимание данной книги часть стандарта MPI – алгоритмы коллективных операций обмена информацией. В следующих главах дается краткое изложение основных понятий стандарта, приводится описание моделей для оценки эффективности алгоритмов и начинается систематическое описание алгоритмов.
