
The CollBook

This work is licensed under a Creative Commons Attribution 4.0 International License (CC BY 4.0). This means you are free to share, copy, redistribute, and modify this book under the following terms:

* Attribution: Credit must be given to the original authors and contributors.
* No Additional Restrictions: You cannot impose legal restrictions that prevent others from using the book freely under the same terms.

Free Digital Version Available. This book is freely available online at https://github.com/happi/theBeamBook/ under the Creative Commons license.

For more information on the Creative Commons license, visit: https://creativecommons.org/licenses/by/4.0/.

Printed edition: Курносов М.Г. *Алгоритмы коллективных операций стандарта MPI*. - Москва: Горячая Линия - Телеком, 2025. - 288 с. ISBN 978-5-9912-1149-9.
// https://www.ozon.ru/product/algoritmy-kollektivnyh-operatsiy-standarta-mpi-2090707135/[Ozon]

© 2025 Mikhail Kurnosov.

[preface]
== Предисловие


Стандарт MPI (Message Passing Interface) и библиотеки реализующие его остаются на протяжении нескольких десятков лет основным средством разработки параллельных программ для высокопроизводительных вычислительных систем с распределенной памятью. Значительное место в стандарте занимает описание коллективных коммуникационных операций, или групповых, глобальных, в которых участвуют все или часть процессов программы. Время их выполнения для многих приложений является критически важным.

Монография, которую вы читаете, – это попытка автора систематизировать и изложить наиболее значимые алгоритмы коллективных операций MPI. Большая часть книги посвящена алгоритмам, которые не учитывают архитектурных свойств вычислительных систем, а опираются лишь на пару двусторонних примитивов передачи Send и приема Recv сообщений. Такие алгоритмы формируют базис для построения более сложных архитектурно-ориентированных методов коллективных операций, построения высокопроизводительных коммуникационных сетей со специализированными топологиями и протоколами канального уровня. Актуальность этих алгоритмов не угасает, с каждым витком развития архитектуры вычислительных систем происходит возврат к базовым алгоритмам и их реализация с учетом текущего уровня развития коммуникационных и процессорных технологий.

Отражены основные подходы построения алгоритмов коллективных операций для систем определенных классов: для системы с общей памятью, иерархические алгоритмы для систем с многоуровневой иерархией памяти и коммуникационной сети. Изложена специфика реализации неблокирующих коллективных операций в библиотеках MPI – построение расписаний и продвижение их выполнения. В конце книги затрагивается вопрос экспериментальной оценки эффективности коллективных операций.

Часть монографии составили результаты исследований, выполненных автором в Сибирском государственном университете телекоммуникаций и информатики (г. Новосибирск) и Институте физики полупроводников им. А.В. Ржанова Сибирского отделения РАН. Описанные практические аспекты реализации алгоритмов опираются на опыт участия автора и его аспирантов в международном проекте Open MPI (компоненты coll/base, coll/libnbc), а также некоторые подходы, которые реализованы автором в серии библиотек структурно-ориентированных алгоритмов коллективных операций MPI по заказу компании Huawei.

Материал книги использовался в курсе лекций "Параллельные вычислительные технологии", который автор читал студентам бакалавриата и магистратуры в Сибирском государственном университете телекоммуникаций и информатики.

В своей профессиональной деятельности автору довелось общаться с большим количеством талантливых людей. Автор благодарен своему научному руководителю чл.-корр. РАН В.Г. Хорошевскому, коллегам по Кафедре вычислительных систем Сибирского государственного университета телекоммуникаций и информатики, а также сотрудникам Лаборатории вычислительных систем Института физики полупроводников им. А.В. Ржанова Сибирского отделения РАН.

Глубокую признательность и благодарность автор выражает всем, кто принял участие в обсуждении рукописи монографии: к.т.н. Полякову Артему Юрьевичу (стандарт PMIx, проекты OpenPMIx, Open MPI; NVIDIA), Аненкову Александру Дмитриевичу (YADRO), д.т.н. Шидловскому Станиславу Викторовичу (Томский государственный университет), к.т.н. Кулагину Ивану Ивановичу (Институт системного программирования им. В.П. Иванникова РАН), д.т.н. доценту Павскому Кириллу Валерьевичу (Институт физики полупроводников им. А.В. Ржанова СО РАН), к.т.н. доценту Пазникову Алексею Александровичу (National University of Singapore).

Автор выражает надежду, что возможные неточности и опечатки в тексте не станут непреодолимой преградой для восприятия основных идей. Замечания, предложения и комментарии можно направить по адресу `+mkurnosov[at]yandex.ru+`.

[.text-right]
С уважением, Михаил Курносов +
профессор, доктор технических наук +
г. Новосибирск
